version: '3.8'

services:

  clickhouse:
    image: yandex/clickhouse-server:22.1
    ports:
      - 8123:8123
      - 9000:9000
    volumes:
      - ./users.xml:/etc/clickhouse-server/users.d/users.xml
      - ./config.xml:/etc/clickhouse-server/config.d/config.xml
#      - ./sample-data.sql:/docker-entrypoint-initdb.d/99-sample-data.sql
      - ./macros.xml:/etc/clickhouse-server/config.d/macros.xml
      - ./init-db.sql:/docker-entrypoint-initdb.d/0-schema.sql
    ulimits:
      nofile:
        soft: 262144
        hard: 262144
    depends_on:
      zookeeper:
        condition: service_healthy

  zookeeper:
    image: "confluentinc/cp-zookeeper:6.2.0"
    hostname: zookeeper
    ports:
      - "2181:2181"
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    healthcheck:
      test: nc -z localhost 2181 || exit -1
      interval: 10s
      timeout: 20s
      retries: 5
      start_period: 10s