keyspace: store
table: products
columnspec:
  - name: product_id
    type: uuid
    generator: uuid
  - name: category_id
    type: bigint
    generator: inc
    min: 1
    max: 3
  - name: product_name
    type: varchar
    generator: constant
    value: 'Product #{category_id} #{ROW}'
  - name: description
    type: varchar
    generator: constant
    value: 'Description #{ROW}'
  - name: price
    type: decimal
    generator: normal(mean=50.0, stddev=10.0)
insert:
  partitions: fixed(10)
  select: fixed(1)/1
